name : Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
    comment-with-action:
      runs-on : ubuntu-latest
      steps:
        - name : "dump github context"
          run: echo "${{ toJson(github.event) }}" | jq
          shell: bash

        - name: Create a comment
          uses: actions/github-script@v3
          with:
            github-token: ${{ secrets.GIT_TOKEN }}
            script: |
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Thanks for opening this issue!'
              })

    comment-with-api:
      runs-on : ubuntu-latest
      steps:
        - name : Create comment with API
          run: |
            curl -X POST -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            --data '{"body":"Thanks for opening this issue!"}'
          
         
        